sudo: required
dist: trusty
language: python
cache: pip
python:
- 2.7
addons:
  postgresql: '9.3'
env:
  - DJANGO_SETTINGS_MODULE=ap.settings.travis
install:
  - pip install -r requirements/dev.txt
before_script:
  - psql -c 'create database djattendance;' -U postgres
  - psql -d djattendance -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  - python ap/makeallmigrations.py
 # - python ap/manage.py makemigrations accounts aputils books classes houses localities rooms services teams terms attendance absent_trainee_roster dailybread leaveslips lifestudies meal_seating schedules syllabus verse_parse
script:
  - python ap/manage.py migrate --noinput
#  - coverage run ap/runtests.py
#  - coverage report
notifications:
  email:
    recipients:
      - attendanceproj@gmail.com
after_success:
#  - coveralls
  - chmod +x selenium_automation.sh
  - ./selenium_automation.sh
deploy:
  provider: heroku
  api_key:
    secure: Erc8ZoPuwl+QTRuOn1pDRRBaLCnYgDPYBSxWbn1OSDei1jfg3euMdIbO1UwBNfpLMeY+VOP9e7YrXa5qdGxEEJdUnY5gQ0K/uYl+Z7juARduabkNZyUV/8tD4zzDo2Fiucvwtk8GF75HmzkED5W316NEnJ00vpBoxIC5ajNw1Qk=
  run:
    - "python ap/makeallmigrations.py"
    - "python ap/manage.py migrate"
    - restart
  app: djattendance
  on:
    repo: attendanceproject/djattendance
    branch: dev
after_deploy:
  - pip install -r requirements/tests.txt
  - ./selenium_automation.sh

