sudo: required
dist: trusty
language: python
cache: pip
python:
- 2.7
addons:
  postgresql: '9.3'
env:
  - DJANGO_SETTINGS_MODULE=ap.settings.travis
install:
  - pip install -r requirements/dev.txt
  - which python
  - mypython=$(which python)
  - sudo $mypython dependencies/ortools/setup.py install
  # Need to reset dir permission b/c ortools generates Errno 13] Permission denied:
  # '.../site-packages/protobuf-3.1.0.post1-py2.7.egg/EGG-INFO/namespace_packages.txt'
  - virtualenvpath=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
  - sudo chmod -R +rw $virtualenvpath
before_script:
  - psql -c 'create database djattendance;' -U postgres
  - psql -d djattendance -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  - python ap/makeallmigrations.py
 # - python ap/manage.py makemigrations accounts aputils books classes houses localities rooms services teams terms attendance absent_trainee_roster dailybread leaveslips lifestudies meal_seating schedules syllabus verse_parse
script:
  - python ap/manage.py migrate --noinput
#  - coverage run ap/runtests.py
#  - coverage report
notifications:
  email:
    recipients:
      - attendanceproj@gmail.com
#after_success:
#  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: Erc8ZoPuwl+QTRuOn1pDRRBaLCnYgDPYBSxWbn1OSDei1jfg3euMdIbO1UwBNfpLMeY+VOP9e7YrXa5qdGxEEJdUnY5gQ0K/uYl+Z7juARduabkNZyUV/8tD4zzDo2Fiucvwtk8GF75HmzkED5W316NEnJ00vpBoxIC5ajNw1Qk=
  run:
    - "python ap/makeallmigrations.py"
    - "python ap/manage.py migrate"
    - restart
  app: djattendance
  on:
    repo: attendanceproject/djattendance
    branch: dev
