language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements/dev.txt
# command to run tests, e.g. python setup.py test
script:  python ap/manage.py test --settings=ap.settings.local
# email notification settings
notifications:
  email:
    recipients:
      - lifeunion@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
# database settings
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
