language: python
python:
  - 2.7
addons:
  postgresql: "9.3"  
install:
  - pip install -r requirements/dev.txt
before_script:
  - cp ap/ap/settings/local.py.example ap/ap/settings/local.py
  - psql -c 'create database ap;' -U postgres
  - sed -i -e 's/getpass.getuser()/"postgres"/g' ap/ap/settings/local.py
  - python manage.py syncdb
script:
  - python ap/manage.py test
# email notification settings
notifications:
  email:
    recipients:
      - lifeunion@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
